[package]
name = "cappy"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
futures = "0.3.31"
memmap = "0.7.0"
tqdm = "0.7.0"
wgpu = { version = "23.0.1", features = ["spirv"] }
