[package]
name = "cappy"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
memmap = "0.7.0"
rand = "0.8.5"
tqdm = "0.7.0"

[build-dependencies]
cc = "*"
